"""
Problem #: 45

https://projecteuler.net/problem=45

Triangluar, Pentagonal, Hexangonal Numbers

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal. 

Answer:  1533776805
Completed on Fri, 17 Dec 2021, 16:25

"""


def prt(a):
    # if type(a) != int:
    #     a = int(a)
    print(f" {a = }", "\n")


p = [int(n * (3 * n - 1) / 2) for n in range(10000, 101000)]
t = [int(n * (n + 1) / 2) for n in range(10000, 101000)]
h = [int(n * (2 * n - 1)) for n in range(10000, 101000)]


intersection = [item for item in p if item in t if item in h]
print(intersection)
